### ISSUE TITLE
运行train.py时出错

### ISSUE THREAD

**Issue by Fuuto-Joker** [DannyLee1991/ExtractTriples#23]
环境：win11 23H2+python 3.7+RTX 3060 Laptop+requirments.txt中的库
运行train.py时报错：
Epoch 1/120
2024-06-06 17:37:20.232084: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2024-06-06 17:37:22.502424: E tensorflow/stream_executor/cuda/cuda_blas.cc:428] failed to run cuBLAS routine: CUBLAS_STATUS_EXECUTION_FAILED
Traceback (most recent call last):
  File "C:\Users\m1879\Desktop\PythonProjects\ExtractTriples\train.py", line 4, in <module>
    train()
  File "C:\Users\m1879\Desktop\PythonProjects\ExtractTriples\kg_with_ds.py", line 391, in train
    callbacks=[evaluator]
  File "C:\Users\m1879\AppData\Local\Programs\Python\Python37\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\m1879\AppData\Local\Programs\Python\Python37\lib\site-packages\keras\engine\training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "C:\Users\m1879\AppData\Local\Programs\Python\Python37\lib\site-packages\keras\engine\training_generator.py", line 217, in fit_generator
    class_weight=class_weight)
  File "C:\Users\m1879\AppData\Local\Programs\Python\Python37\lib\site-packages\keras\engine\training.py", line 1217, in train_on_batch
    outputs = self.train_function(ins)
  File "C:\Users\m1879\AppData\Local\Programs\Python\Python37\lib\site-packages\keras\backend\tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "C:\Users\m1879\AppData\Local\Programs\Python\Python37\lib\site-packages\keras\backend\tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "C:\Users\m1879\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\client\session.py", line 1472, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.InternalError: 2 root error(s) found.
  (0) Internal: Blas GEMM launch failed : a.shape=(8000, 256), b.shape=(256, 128), m=8000, n=128, k=256
	 [[{{node dense_1/MatMul}}]]
	 [[loss/add/_1423]]
  (1) Internal: Blas GEMM launch failed : a.shape=(8000, 256), b.shape=(256, 128), m=8000, n=128, k=256
	 [[{{node dense_1/MatMul}}]]
0 successful operations.
0 derived errors ignored.
请问在哪修改、怎么修改代码能解决这种问题？

**Comment by jds78** [comment]
Epoch 1/120
2025-06-26 20:53:51.194759: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2025-06-26 20:53:53.969238: E tensorflow/stream_executor/cuda/cuda_blas.cc:428] failed to run cuBLAS routine: CUBLAS_STATUS_EXECUTION_FAILED
2025-06-26 20:53:53.969483: I tensorflow/stream_executor/stream.cc:1990] [stream=0x31da8540,impl=0x31be2580] did not wait for [stream=0x31d9c260,impl=0x31d9a7d0]
2025-06-26 20:53:53.969557: I tensorflow/stream_executor/stream.cc:4925] [stream=0x31da8540,impl=0x31be2580] did not memcpy device-to-host; source: 0x7fd4f7a82b00
2025-06-26 20:53:53.969685: F tensorflow/core/common_runtime/gpu/gpu_util.cc:293] GPU->CPU Memcpy failed
2025-06-26 20:53:53.969684: I tensorflow/stream_executor/stream.cc:4925] [stream=0x31da8540,impl=0x31be2580] did not memcpy device-to-host; source: 0x7fd4f6df5d00
已放弃 (核心已转储)
同问
